language: node_js

node_js:
  - stable

sudo: false

cache:
  directories:
    - "node_modules"

script:
  - npm test -- --coverage

after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls

branches:
  only:
    - master